apiVersion: v1
description: wordsmith-api helm chart
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: wordsmith-api
appVersion: {{version}}
version: {{version}}
