replicaCount: 1
image:
  repository: cleclerc/wordsmith-api
  tag: {{version}}
  pullPolicy: IfNotPresent
service:
  name: wordsmith-api
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
ingress:
  enabled: true
  hosts:
  - api.staging.wordsmith.beescloud.com
  annotations:
database:
  url: jdbc:postgresql://wordsmith-staging.ca3tifbqfpuf.us-east-1.rds.amazonaws.com:5432/wordsmith
  username: root
  password: password