{{- if .Values.ingress.enabled -}}
{{- $defaultFullName := template "fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default $defaultFullName | quote }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
